package com.deepika.list_test_rm_proj_multifire_scntwo;

import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class combined_pojo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public combined_pojo() {
    }
    
    private java.util.List<java.lang.String> UDC = new ArrayList<String>();
    private java.util.List<java.lang.String> secondList = new ArrayList<String>();
    
    private java.math.BigDecimal data_ppmonth;
    
    public java.math.BigDecimal getData_ppmonth() {
		return data_ppmonth;
	}
	public void setData_ppmonth(java.math.BigDecimal data_ppmonth) {
		this.data_ppmonth = data_ppmonth;
	}
	
    private java.lang.String strVal;
	public java.lang.String getStrVal() {
		return this.strVal;
	}

	public void setStrVal(java.lang.String strVal) {
		this.strVal = strVal;
	}


public java.util.List<java.lang.String> getSecondList() {
		return this.secondList;
	}

	public void setSecondList(java.lang.String input) {
			this.secondList.add(input);
	}


public java.util.List<java.lang.String> getUDC() {
		return this.UDC;
	}

	public void setUDC(java.lang.String input) {
			this.UDC.add(input);
	}
	
	//public java.util.List<java.lang.String> removeAllElementsOfList(java.util.List<java.lang.String> listVal){
	  //  listVal.removeAll(listVal);
	   // return listVal;
//	}

public void updateList(java.util.List<java.lang.String> inpiutList){
    inpiutList.removeAll(inpiutList);
}

private java.util.List<java.lang.String> UDC1 = new ArrayList<String>();


	public java.util.List<java.lang.String> getUDC1() {
		return this.UDC1;
	}

	public void setUDC1(java.lang.String input) {
			UDC1.add(input);
	}
	

}